# render.yaml
services:
  - type: web
    name: my-django-app
    env: python
    buildCommand:
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn namknights.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: namknights.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString
