# Generated by Django 5.2.1 on 2025-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('Shirt', 'Shirt'), ('Coin', 'Coin'), ('Other', 'Other')], default='Shirt', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(blank=True, help_text='Size (e.g., S, M, L, XL). Only for shirts.', max_length=10, null=True)),
                ('color', models.CharField(blank=True, help_text='Color (optional). Only for shirts.', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
