# Generated by Django 5.2.1 on 2025-05-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format (555) 555-5555', regex='^\\(\\d{3}\\) \\d{3}-\\d{4}$')])),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zip code', regex='^\\d{5}(-\\d{4})?$')])),
                ('type_of_assistance', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Monetary', 'Monetary'), ('Attend Event', 'Attend Event'), ('Escort', 'Escort'), ('Other', 'Other')], max_length=20)),
                ('assistance_description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('has_viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format (555) 555-5555', regex='^\\(\\d{3}\\) \\d{3}-\\d{4}$')])),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zip code', regex='^\\d{5}(-\\d{4})?$')])),
                ('motorcycle_make', models.CharField(max_length=100)),
                ('motorcycle_model', models.CharField(max_length=100)),
                ('military_service', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('military_branch', models.CharField(blank=True, choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('Marines', 'Marines'), ('Coast Guard', 'Coast Guard'), ('Space Force', 'Space Force'), ('Other', 'Other')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('has_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
